# Generated by Django 4.2.2 on 2023-10-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='choice',
            field=models.CharField(choices=[('P', 'provider'), ('C', 'consumer')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
