# Generated by Django 4.2.2 on 2023-10-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiuser_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='goods',
            field=models.JSONField(default=dict),
        ),
    ]
