# Generated by Django 4.2.2 on 2023-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storage_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='toandfromstorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
